#########################################################################
#
# Environmental monitoring using ESP32-S3 chipset and BME280 sensor(s)
# for temperature, humidity, pressure & dew point.
#

   # Provides substitutions or variables that are then called elsewhere multiple times in the config
substitutions:
   # Default name  
  name: "sitename-decontamination-station"
   # Default friendly name 
  friendly_name: "Sitename - Decontamination Station"
   # Description as appears in ESPHome & top of webserver page
  device_description: "Decontamination Station - Water & Environmental Monitor (Temp./Humidity/Pressure)"
   # Project Name
  project_name: "Aviagen.Decontamination Station"
   # Project version denotes the release version of the yaml file, allowing checking of deployed vs latest version
  project_version: "0.1.0"

   # If true, entity should not be added to Home Assistant frontend, without the user manually enabling it.
  disable_by_default: "false"

###############################
# BME 280 / BME680 Sensor
#
   # Location of BME280/680 Sensor #1. Used to prefix sensor if there are two. Leave empty if only 1. Add a " - " to the end of each entry if used.
  bme_sensor1_location: ""
   # Location of BME280/680 Sensor #2. Used to prefix sensor if there are two. Leave empty if only 1. Add a " - " to the end of each entry if used.
  bme_sensor2_location: ""
   # Calibrate the outpute of the temperature sensor(s).
  temperature_1_offset: "0.0"
  temperature_2_offset: "0.0"
   # Calibrate the outpute of the pressure sensor(s).
  pressure_1_offset: "0.0"
  pressure_2_offset: "0.0"
   # Calibrate the outpute of the humidity sensor(s).
  humidity_1_offset: "0.0"
  humidity_2_offset: "0.0"


########################## End of Substitutions #########################
#
# Defines the type of ESP chip used on the device. 
# Must be in the local devices configuration file.
#

#esp32:
#  board: esp32-s3-devkitc-1
#  framework:
#    type: arduino

#########################################################################
#
# Remote Packages to be utilised
#

dashboard_import:
  package_import_url: github://roving-ronin/aviagen/esphome/decontamination-station.yaml@main
  import_full_config: false

packages:
  base-config:            !include common/base-configuration.yaml
  network-config:         !include common/network-ethernet.yaml
  bme280a-sensors:        !include sensors/bme280-bus-a.yaml
# bme280b-sensors:         !include sensors/bme280-bus-b.yaml  # Enabled if a second i2c bus and BME280 is required
  kincony-esp32-s3-core:  !include boards/kincony-esp32-s3-core.yaml


#########################################################################
